### ISSUE TITLE
Provide a package on PyPI

### ISSUE THREAD

**Issue by bobturneruk** [Mesnage-Org/pgfinder#10]
This would mean people familiar with installing packages could use the software (would need to be open source see issue #6 ).

**Comment by ns-rse** [comment]
This will require the registration of a [generic email account](https://shef.topdesk.net/tas/public/ssp/content/detail/knowledgeitem?unid=94dc79f1c7404d70b1af0457c2763b90) e.g. `pgfinder@sheffield.ac.uk` as a valid email address is required for registering and submitting packages to PyPi for publication/sharing.

I can be the person who receives emails sent to `pgfinder@sheffield.ac.uk` in the first instance whilst we get things up and running.
