### ISSUE TITLE
Submit PGFinder work to JOSS

### ISSUE THREAD

**Issue by smesnage** [Mesnage-Org/pgfinder#109]
No rush on this but it would be great to add another reference to the literature when we wrap up the next application. 
eLife and our next publication  will give us scientific credentials
Joss will tell reviewers we applied high coding standard.

**Comment by ns-rse** [comment]
The [Journal of Open Source Software Submission Page](https://joss.theoj.org/papers/new) has all the information we need to get started on this.

They provide a [markdown and .bib template](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography) and request it works with the [Open Journals PDF Generator GitHub Action](https://github.com/marketplace/actions/open-journals-pdf-generator).

I've added templates and the Action to the `109-joss` branch and will endeavour to get a skeleton in place over the coming weeks as time permits.

**Comment by TheLostLambda** [comment]
Submission is done! Now, we wait...

**Comment by ns-rse** [comment]
What branch was noted in the submission and the current paper and documents on? I have `ns-rse/109a-joss` branch with `joss/paper.{bib,md}` on but both it and the `109-joss` branch are waaay out of date and there isn't anything on `main`.

**Comment by TheLostLambda** [comment]
The paper is in the 109-joss branch, but I don't think they look at the code on the paper branch? Maybe to be safe I can try to rebase it...

**Comment by TheLostLambda** [comment]
Actually looks like I've already done that — whoops!

The PR shows only the paper files are new (even though the commits are still a bit different from `master`...

https://github.com/Mesnage-Org/pgfinder/pull/130/files

**Comment by ns-rse** [comment]
Thanks @TheLostLambda and apologies for not checking the PR this week, I've been on leave.
