### ISSUE TITLE
Extend readme

### ISSUE THREAD

**Issue by bobturneruk** [Mesnage-Org/pgfinder#12]
Provide gentler install instructions

**Comment by ns-rse** [comment]
I think the installation instructions are pretty comprehensive at the moment (see [installation](https://mesnage-org.github.io/pgfinder/installation.html)).

There is however the need to expand on the [introduction](https://mesnage-org.github.io/pgfinder/introduction.html) section with some overview of peptidoglycan analysis. I've created #105 to specifically address that.
