### ISSUE TITLE
Enable PGFinder to queue searches (multiple FTRS files with one given database) 

### ISSUE THREAD

**Issue by smesnage** [Mesnage-Org/pgfinder#129]
We currently have enzymatic assays (n=48) that need to be search by the same database(s). This currently requires 48 (excruciating) individual searches through the Jupiter notebook (the plebs has no other choice) and downloads.
Having all search outputs in ONE excel file containining multiple tabs would be fab.

**Comment by bobturneruk** [comment]
I'm going to add a private repo to @mesnage-org that may help with this.

**Comment by smesnage** [comment]
Should this Issue be deleted? 
The new GUI enables to queue searches

**Comment by TheLostLambda** [comment]
Even though there is polish to be done, the GUI issue was closed, so this should be as well!
