### ISSUE TITLE
Error message in mybinder

### ISSUE THREAD

**Issue by bobturneruk** [Mesnage-Org/pgfinder#133]
When trying to analyse any ftrs file

![image](https://user-images.githubusercontent.com/34244196/203819115-beb97cd2-877e-4128-bbbf-a8020e49cf87.png)

**Comment by bobturneruk** [comment]
Temporary fix:

https://github.com/Mesnage-Org/pgfinder/tree/bobturneruk/133-mybinder-error

https://hub.gke2.mybinder.org/user/mesnage-org-pgfinder-5z25cvz1/notebooks/pgfinder_interactive.ipynb

**Comment by bobturneruk** [comment]
Not 100% sure but could be due to a major version increase on ipywidgets https://github.com/jupyter-widgets/ipywidgets

**Comment by smesnage** [comment]
Hi,

Still a problem. It works if you use a default database but does not if you use a custom one
See error message below, I don't know if this is trivial or not.

![Error](https://user-images.githubusercontent.com/70374280/205342878-7361f84e-a3c6-4bfc-8828-83800a1e3327.PNG)

**Comment by TheLostLambda** [comment]
Solved the issue!

These couple of lines in `pgfinder/pgio.py` need changing from:
```py
filename = list(upload.keys())[0]
file_contents = upload[list(upload.keys())[0]]["content"]
```
To:
```py
filename = upload["name"]
file_contents = upload["content"]
```
It also makes that so hated line of code a bit less hateable!

Hopefully this helps some!
Brooks
