### ISSUE TITLE
Running interactive notebook locally

### ISSUE THREAD

**Issue by bobturneruk** [Mesnage-Org/pgfinder#136]
This needs the folloiwing syntax:

```
jupyter notebook --config="jupyter_notebook_config.py" .\pgfinder_interactive.ipynb
```

and potentially some extra installation steps.

**Comment by TheLostLambda** [comment]
Shall we try to preserve the spirit of this, but using the new JupyterLite notebook?

**Comment by bobturneruk** [comment]
I'd close this - the notebook runs locally with JupyterLite already.

**Comment by TheLostLambda** [comment]
Sounds good to me!
