### ISSUE TITLE
Jupyter notebook display

### ISSUE THREAD

**Issue by smesnage** [Mesnage-Org/pgfinder#137]
User feedback (Richard!) suggested to display the name of the FTRS file uploaded and name of the database file.
Let me know if this does not make sense, I'll explain what I meant.

**Comment by TheLostLambda** [comment]
Zoom! Caught me in a coding mood! Is this what you're looking for?


https://user-images.githubusercontent.com/6251883/212491340-0793c5e0-e680-40e3-923e-181015af82c2.mp4


If so, here is the code for @bobturneruk to help me sanity-check:
```python
# Deconvoluted Data file upload
file_upload = widgets.FileUpload(
    accept = '.txt,.ftrs', 
    description = 'Upload Deconvoluted Data',
    multiple = False,
    layout = big_button
)
file_name = widgets.Label(value="No file selected...")
def handle_file_change(file):
    file_name.value = file["new"][0]["name"]
file_upload.observe(handle_file_change, names='value')
data_uploader = widgets.HBox([file_upload, file_name])
```

**Comment by smesnage** [comment]
Looks good to me, yep, this is what I meant!

**Comment by bobturneruk** [comment]
Could you turn this into a PR, please, @TheLostLambda ?
