### ISSUE TITLE
Support multiple versions of documentation on GitHub Pages

### ISSUE THREAD

**Issue by ns-rse** [Mesnage-Org/pgfinder#143]
Use the [sphinxcontrib-versioning](https://github.com/sphinx-contrib/sphinxcontrib-versioning) extension to support multiple versions of documentation hosted on GitHub Pages.

**Comment by ns-rse** [comment]
[`sphinxcontrib-versioning`](https://github.com/sphinx-contrib/sphinxcontrib-versioning/) doesn't work with Sphinx > 2.0 (see [issue 77](https://github.com/sphinx-contrib/sphinxcontrib-versioning/issues/77)) which has languished for some time.

An alternative is to use [sphinx-multiversion](https://holzhaus.github.io/sphinx-multiversion/master/index.html).

**Comment by TheLostLambda** [comment]
Is this another issue that can now be closed?

**Comment by TheLostLambda** [comment]
Closing as a potential duplicate of #228
