### ISSUE TITLE
Issue related #81 (Just closed!); new formatting incompatible with consolidation

### ISSUE THREAD

**Issue by smesnage** [Mesnage-Org/pgfinder#145]
Looking at the current output of the search, I'm afraid it does not work! Just a reminder of how we got there:
![image](https://user-images.githubusercontent.com/70374280/232899376-ae14bbdc-cd7f-4898-be96-63b0232a480a.png)
 
Explaining why it does not work is quite complicated so I have attached a file comparing the outputs: (i) the original one, (ii) what I suggested and 'iii) after long format.
I think the final display needs to be changed. happy to chat with you (Neil) if what I'm saying does not make sense!
Being able to consolidate the data is critical so unless we fix this, PGFinder is broken.

[Long.format.issue.with.consolidation.xlsx](https://github.com/Mesnage-Org/pgfinder/files/11271842/Long.format.issue.with.consolidation.xlsx)

**Comment by TheLostLambda** [comment]
@ns-rse To add a bit here, I think we should add a flag for long / wide output and just add a pass at the end for generating wide outputs from the existing long format. I think everything internally should use the long format (and I'd personally vote for that remaining the default), but a boolean flag and a checkbox on the notebook for wide output seems like a decent stop-gap solution!

Shouldn't be too much pandas work to group rows by ID and merge those rows' structure and ppm lists.

In the medium-term it might be worth having a chat with Steph about this consolidation process and adding an optional step in the PGFinder pipeline for doing this consolidation automatically (saving people a lot of Excel time!)

**Comment by ns-rse** [comment]
Thanks @smesnage I look into this. I think understanding this consolidation step would be important as it can be automated, e.g. the rules look like `=L9+L10` for the **original suggestion** section was derived based on the smallest `delta-ppm` but its not clear where the `3.81E06` comes from.

I've put a meeting in for tomorrow and we can go through it if that's ok, quicker and no doubt clearer than messaging here/emails.

@TheLostLambda That makes sense, long internally makes life considerably easier. Reshaping from long to wide for output at the end is straight-forward (and if its essential to have columns concatenated that can be done too). Included you in the invitation tomorrow if you want to come along too.

**Comment by smesnage** [comment]
I modified the example file above to explain why I wanted to add the ppm column, describing what I wanted to add as the next step.
Basically, when an observed mass can correspond to 2 structures, we can use the delta ppm value to chose the most likely one.
I hope this makes sense!

**Comment by smesnage** [comment]
I have attached the latest version of the excel file we looked at this afternoon.
[Long.format.issue.with.consolidation.xlsx](https://github.com/Mesnage-Org/pgfinder/files/11287033/Long.format.issue.with.consolidation.xlsx)

**Comment by ns-rse** [comment]
Commit [716b378](https://github.com/Mesnage-Org/pgfinder/commit/716b378a2d95b79ada05edbbad09c18d8444d49a) produced a work in progress Notebook for the branch [ns-rse/145-consolidation-formatting](https://mybinder.org/v2/gh/Mesnage-Org/PGFinder/ns-rse/145-consolidation-formatting?urlpath=tree/pgfinder_interactive.ipynb).

Subsequent feedback (via email).

# Lowest PPM occurs more than once

![image](https://user-images.githubusercontent.com/17566406/236472091-77bda4bf-b5cf-4116-9617-3b301107e944.png)

Big, fundamental issue should only be once per matched `inferred structure` column.

**IMPORTANT** 

> Re-lowest ppm: Marcel pointed out that what is important is the lowest ABSOLUTE VALUE of delta ppm, not lowest. For example, out of the 3 structures below, the one highlighted is the one you need to pick.
| Structure |                                   Dppm |
| `GM-AEJAA|1` |                              -1.38887 |
| `GM-AEJAA|1` |                              -1.08745 |
| `GM-AEJAA|1`  |                             -0.54488 |

> Bottom row is the best match as its closest to zero.

Already using Pandas [.abs()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.abs.html) method to ensure absolute values are obtained.


## I would remove the last column "Inferred Max intensity"; is it possible?

Yes, line commented and removed.

## Can you show RT with 2 decimals only? ppm with 1 decimal only? Intensity in scientific format?

Formatting is configurable across all floats but not on an individual basis at the moment. Agreed to drop this from priority work for now.

## Consolidation not yet working

![image](https://user-images.githubusercontent.com/17566406/236474187-abaedc82-7e3c-4928-acab-7324f513c9cf.png)


Contingent on first problem being solved correctly

## Can we add the version of the script in the metadata (cell A1 in the output?)

Yes, I can include the version which includes the git commit and makes things uniquely identifiable.

**Comment by smesnage** [comment]
I'm a bit lost in the issues that have been fixed or are being fixed but here's the major issue I ran into when I used the script yesterday. A lot of matches are duplicated

We need to fix the final output and display results AS WE DID BEFORE long format was introduced, lumping together matches that corresponds to the same theoretical mass:

	6720	15.292683	16.577671	250	3;2;1	15.72019652	1864.806736	1864.8047	1.091872495	gm-AEJA-gm-AEJA|2	9.527E+08
	6720	15.292683	16.577671	250	3;2;1	15.72019652	1864.806736	1864.8048	1.038247521	gm-AEJAA-gm-AEJ|2	9.527E+08
Should be

	6720	15.292683	16.577671	250	3;2;1	15.72019652	1864.806736	1864.8047	1.091872495	gm-AEJA-gm-AEJA|2, gm-AEJAA-gm-AEJ|2	9.527E+08

Sorry if this is already on your list!!

**Comment by TheLostLambda** [comment]
Sounds like after meeting today, the plan is to add a post-processing step (toggleable by a flag or option somewhere) to squishing this long format back into cells separated with commas!

As ugly as it is, if we're doing anything with wide format, I might lean towards the comma solution (over adding any columns) since it keeps the table "schema" the same (always a known number of columns). It also seems very rare that those comma-separated cells are ever split!

Let me know @ns-rse once you've made some progress or if there is anything I can help with!
