### ISSUE TITLE
Retain multiple matches when difference is < 1ppm

### ISSUE THREAD

**Issue by ns-rse** [Mesnage-Org/pgfinder#152]
From @smesnage 

>  In some cases, the ∆ppm value is so close that choosing one structure rather than the other is not right so it is best to NOT pick one structure. I would argue that if 2 theoretical masses are less than 1 ppm apart, it is better to keep both structures.
> For a limited number of structures, this is the case. I would say that if the absolute value of ∆ppm is not more than 1ppm, then this should be treated as a mass coincidence, so it could be either of the structures matched!

To clarify I've understood correctly...

* If the ∆ppm differs between two matches but that difference is < 1ppm they should be treated as though they are identical and both matches should appear in the "Most likely structure".

This raises the question of which "Intensity" should be shown/retained. It might seems simple to reshape the "Intensity" in the same manner, separating the matches by `",   "`, however this would then cause problems if the cells were to be summed during consolidation as any such cells would then be strings rather than integers/floats (i.e. non-numeric).

**Comment by TheLostLambda** [comment]
Hi Neil!

I think you've got the right idea about the <1ppm difference! I may be missing a bit, but I think "Intensity" should be identical? Since we should only be taking rows from the same match ID?
If you mean which ppm to pick, I think my other email I just sent should address that!
Let me know if I'm missing something!
Brooks

**Comment by ns-rse** [comment]
You're right @TheLostLambda I realised the other day that Intensity will remain the same!

**Comment by TheLostLambda** [comment]
Is this a change that's addressed in the latest PR then? Or does this issue still need to be open to add the feature separately? Perhaps via that group-minimum-filter method?

**Comment by TheLostLambda** [comment]
Reopening this for the time being until I know the status of this feature :)

**Comment by TheLostLambda** [comment]
Notes to self:

![image](https://github.com/Mesnage-Org/pgfinder/assets/6251883/7e156cd6-3d13-4279-b57d-3e09302ff35b)

**Comment by TheLostLambda** [comment]
Another note, this should be user configurable (so that you can essentially deactivate the pick-lowest-ppm feature by setting it's ppm to the overall search ppm)
