### ISSUE TITLE
Explore Replacing JupyterLite With a Proper Web UI + Pyodide

### ISSUE THREAD

**Issue by TheLostLambda** [Mesnage-Org/pgfinder#166]
Not sure how much room there is for improving here, but it would be nice to see if we could get away with adding a button to reanalyze the data after a first result has been returned (instead of just a single button for downloading the last run, I suppose I'll need a list of things to download for the sake of #129)

What I'd like to do after that is add in some fancy JS that can check if the cache needs clearing too... I think we might only need to clear part of IndexedDB, but it feels almost possible to automate version checking and clear the cache when needed (or at least display a message and give a button for doing so. This was the inspiration: https://github.com/jupyterlite/jupyterlite/issues/407#issuecomment-1353088447

I'd like to make it possible to sit down, press run on all cells (no way to autorun them?), then make it so you're able to run as many searches as you'd like without restarting or refreshing, running, or cache-clearing.

We'll see how much of that is feasible?

**Comment by bobturneruk** [comment]
I would leave this as a low priority - Jupyter is already being pushed quite hard here in terms of acting like a GUI.

**Comment by TheLostLambda** [comment]
I think that seems reasonable! Maybe it's also worth looking into a proper website / running our own Pyodide in WASM! I've made some webtools that run WASM before (in Rust) so maybe that's not a bad idea (since what it sounds like we actually want is a GUI anyways!)

**Comment by TheLostLambda** [comment]
As some longer-term notes then, I'll drop a link to some resources:
- https://www.skeleton.dev/ (For a nice UI library)
- https://pyodide.org/en/stable/index.html (Docs for Pyodide itself)
- https://pyodide.org/en/stable/usage/loading-packages.html#installing-packages (For installing pgfinder)
- https://www.nextflow.io/index.html (an alternative way to run things, but not a GUI)

**Comment by TheLostLambda** [comment]
If this goes well in the end, I should refactor the `...upload_reader` functions in `pgio.py` so that they take name and content as separate arguments — the odd dictionary method of passing arguments seems to just be a carry-over from ipywidgets

**Comment by ns-rse** [comment]
@TheLostLambda : Can this be closed in light of [pgfinder-gui](https://github.com/Mesnage-Org/pgfinder-gui/)?

**Comment by TheLostLambda** [comment]
Hi @ns-rse ! There is certainly still some work to the done on the UI, but I think it's more than enough to consider this issue closed :)
