### ISSUE TITLE
Brooks's Week of the 19th Hackathon Task List

### ISSUE THREAD

**Issue by TheLostLambda** [Mesnage-Org/pgfinder#167]
Hi @smesnage @ns-rse @bobturneruk !

I think (because I will be using a lot more PGFinder in the near future), that I'd like to spend some of this upcoming week (commencing the 19th of June) 100% on crushing PGFinder bugs + adding quality of life features!

My current priorities:
- [x] #106
- [x] #152
- [x] #166 
- [x] #129 
- [ ] #114
- [ ] #113
- [x] #164
- [ ] #168
- [x] #176 

If people have opinions on what they'd like me to focus on, just let me know! And if there is something you'd like to sneak on to my list, please do so ASAP!

**Comment by TheLostLambda** [comment]
And a note to myself, does the multimer builder only build multimers out of monomers that have been found? Or does it just build multimers out of everything in the database?

It would be nice if PGFinder did a bit of the sanity-checking itself (if that's not already the case)

**Comment by smesnage** [comment]
Eeeek, see Patel et al!!
It only uses monomers found as acceptors, building 3-4 and 3-3 dimers (X-gmAEJA and x-gm-AEJ)

**Comment by TheLostLambda** [comment]
> Eeeek, see Patel et al!! It only uses monomers found as acceptors, building 3-4 and 3-3 dimers (X-gmAEJA and x-gm-AEJ)

Ah, that's why I asked, because I remembered reading that sequential diagram in the paper, but forgot if that was done in code or something the user had to do!

That should would mean that my mass-library creation was pointless then :sweat_smile: Since I was just feeding the monomers back into as a mass library. Should give the same results if I just start with Multimers enabled!

**Comment by smesnage** [comment]
I'm 100% supportive of the Hackathon!!
Not quite sure how I can help though. Neil and Bob have phased out (as planned) but hopefully we can beg for a quick favour if PR are a simple formality. Or maybe you can ask Ankur?
FIngers crossed to get the next slice of funding to get more stuff done. There is some money on the Rhizobium grant so if you struggle on your own we can call for rescue but I would rather not start any major task.
This long format stuff (which was a massive step forward) was supposed to be simple...

**Comment by bobturneruk** [comment]
I don't mind looking at PRs when I have a spare minute. I always learn from this.

**Comment by ns-rse** [comment]
Happy to review PRs too. :+1:

**Comment by TheLostLambda** [comment]
Gotten a bit of a late start to things here, but planning to start in full-force tomorrow and run through the weekend / a bit into next week!

**Comment by TheLostLambda** [comment]
Closing this, since the few tasks left have been transferred to the v1.0.0 milestone!
