### ISSUE TITLE
PGFinder needs sqlite3 as a dependency?

### ISSUE THREAD

**Issue by TheLostLambda** [Mesnage-Org/pgfinder#170]
Mostly a question for @bobturneruk and @ns-rse who I know have battled with this before! I remember us removing `pysqlite3` from the dependencies at some point, but I don't think we ever replaced it in the pip package with `sqlite3`!

I'm currently needing to install `sqlite3` to get things working in my pyodide instance at the moment, just wanted to double-check if there was any reason that I shouldn't add that dependency to https://github.com/Mesnage-Org/pgfinder/blob/master/pyproject.toml ?

**Comment by TheLostLambda** [comment]
Hahaha, whoops! Nevermind... It still needed to be loaded in Pyodide, but it's part of the standard library and definitely shouldn't be added to the pyproject.toml file :sweat_smile:

**Comment by ns-rse** [comment]
Glad you've sorted this one @TheLostLambda `sqlite3` it is indeed part of the standard library.
