### ISSUE TITLE
Look into Poetry as a build / dependency managment system

### ISSUE THREAD

**Issue by TheLostLambda** [Mesnage-Org/pgfinder#188]
Seems to be the only nice way to do Python dependency management / environments without hacking things together yourself!

**Comment by bobturneruk** [comment]
No it's not it's horrible.

**Comment by TheLostLambda** [comment]
Haha, uh oh! That's good to know as I've not actually used it yet! What sort of issues have you had with it?

**Comment by bobturneruk** [comment]
If there must be a heavyweight solution, this is likely the way to go https://pdm.fming.dev/latest/

Lack of Conda support in Poetry is a deal-breaker for many research applications.

**Comment by bobturneruk** [comment]
Poetry is great for web apps with lots of devs.

**Comment by bobturneruk** [comment]
This is my opinion.

**Comment by TheLostLambda** [comment]
Seeing as pgfinder doesn't have any Conda dependencies (?), would it still be something reasonable to use here? Or no? I'm essentially just thinking as a way to ease the dependency installation which has me currently installing virtualenv's manually followed by `pip install -e .`

Seems like a decently nice CLI for a "simpler" (dependency-wise) project like pgfinder, though I may be missing something!

**Comment by bobturneruk** [comment]
Try installing Poetry on a machine that also has Conda.

**Comment by TheLostLambda** [comment]
I've sorted out something on my end with Nix, so I'm not to fussed about changing things anymore! Good to know that Poetry isn't all roses and buttercups! (If that's how that idiom goes...)
