### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by bobturneruk** [Mesnage-Org/pgfinder#2]
This might be a good way to implement a GUI.

https://www.datacamp.com/community/tutorials/learn-build-dash-python

It would require some refactoring of the current code (basically pulling load and save operations out of the main script so they can be called in different ways).

**Comment by bobturneruk** [comment]
Now have an end-to-end demo using binder

**Comment by bobturneruk** [comment]
Next step is to allow user input.

**Comment by Ankur-AVP-Patel** [comment]
GUI implemented via jupyter notebook
