### ISSUE TITLE
Merge `pgfinder-gui` into the `pgfinder` repository

### ISSUE THREAD

**Issue by TheLostLambda** [Mesnage-Org/pgfinder#206]
I've done a bit of thinking, and I think the best way forward here might be a monorepo approach. There are some things I've been doing currently that just don't make sense.

For example, every time any of the API changes on the PGFinder side (like when I recently added the new "Consolidation PPM" option), I need to add some UI to the other repository. Fundamentally, both of these changes are coupled — I can't publish a working GUI without first publishing a PGFinder patch that breaks the current / old GUI.

There is also a gap in CI testing of the UI following changes to PGFinder. If part of the PGFinder GUI shim is changed, none of the CI in this repository can catch bugs. I have to manually copy a wheel and test things locally if I want to be confident things are working. This led to me pushing a couple of broken versions to someone using PGFinder recently because CI in this repo is GUI-blind.

I also think it makes more sense for these components to live together, since historically the Jupyter notebooks lived here. The GUI and PGFinder are tightly coupled, so the repo structure should reflect that (especially if GUI docs are supposed to live in this repository!)

I also think this would be a change that makes things a lot nicer for the JOSS people, so I'm going to mark this as "JOSS Essential", but I'll await at least some feedback from @bobturneruk before embarking on this mission...

**Comment by TheLostLambda** [comment]
As an excellent example of why these two repositories should probably be merged, several issues on the `pgfinder-gui` repository could be closed or at least partially addressed by the merger as well:

- https://github.com/Mesnage-Org/pgfinder-gui/issues/8
- https://github.com/Mesnage-Org/pgfinder-gui/issues/6

**Comment by TheLostLambda** [comment]
Biggest struggle here is probably going to be sorting out the GitHub Pages so that the UI and documentation can be hosted from the same place...

**Comment by TheLostLambda** [comment]
If this merge is possible, it would be nice to see if some CI magic can be done to bundle the latest PGFinder wheel into the GUI — that way we don't have to even rely on PyPi?

**Comment by bobturneruk** [comment]
I think for a project this scale a single repo is probably a fine plan. Whether we want to cut PyPI out of the loop, I'm not sure. But I reckon we can make the CI do what you want.

Keeping the "library" independent of the UI is still wise. It would be nice to see it possible for `pgfinder` to be built into bigger workflows / different interfaces. I think if changes to the science in the library force UI changes, that's OK, if it's the other way round it's worrying.

In general, the monolith vs. microservices debate will continue on way past my retirement.

**Comment by TheLostLambda** [comment]
I definitely agree we should keep the library and UI logically separated! I'm thinking keeping them in totally separate folders still, with shared things like the license, etc in the top-level directory! I'm hoping to still keep them apart conceptually, but I think merging them into the same repo will make their development easier (PRs can change the UI to not break with new PGFinder versions in a single place).

In hindsight, I think keeping PyPi in the loop is still a good idea for now — that way we are still shipping stable versions of the library and CLI. Also, if the GUI is only pulling stable versions, it lets us ensure that changes on `master` aren't leaking into the GUI before they are part of a release.

Here is the "helpful" flowchart that I used when considering this particular case:
![image](https://github.com/Mesnage-Org/pgfinder/assets/6251883/922b2c41-6336-4684-9b89-e639e7f962ee)
