### ISSUE TITLE
Fix ORDA Release CI?

### ISSUE THREAD

**Issue by TheLostLambda** [Mesnage-Org/pgfinder#213]
I think this is something @ns-rse would know best about?

**Comment by bobturneruk** [comment]
I can probably help - what's the problem, please?

**Comment by TheLostLambda** [comment]
Twofold!

1. I have no idea what we're supposed to be uploading to ORDA / how to do so
2. But what's actually triggered this issue is this: https://github.com/Mesnage-Org/pgfinder/actions/runs/6058111672

The deploy failed for one reason or another (it might be that my GitHub account doesn't have permissions?), and I'm not certain how to fix it!

**Comment by ns-rse** [comment]
I've encountered this in a few places, the uploads fail as connections sometimes timeout or in this case the connection has been reset. I've not come up with a permanent solution to it yet beyond re-running the failed job which is not ideal. Will see if I can find a better solution.

**Comment by ns-rse** [comment]
Re-running and it completed with no obvious change :shrug: 

It may just be something we have to live with, timeouts could be caused at the ORDA/figshare end at Uni.

**Comment by TheLostLambda** [comment]
Fascinating, well, I reckon this can be closed then — we'll just have to keep a bit of an eye on it...
