### ISSUE TITLE
Input validation

### ISSUE THREAD

**Issue by bobturneruk** [Mesnage-Org/pgfinder#22]
Code will take `.csv` files as input - we need checks to make sure these import with the correct columns and data types, and sensible error messages.

**Comment by Ankur-AVP-Patel** [comment]
Will work on this either later today or Monday

**Comment by bobturneruk** [comment]
It seems like the entry points requiring validation are:

- [ ] `matching.ftrs_reader()`
- [ ] `matching.data_analysis()`

**Comment by bobturneruk** [comment]
Largely resolved by https://github.com/Mesnage-Org/pgfinder/pull/36

A new issue should be raised if more validation is needed.
