### ISSUE TITLE
A petty bug! Change typpos

### ISSUE THREAD

**Issue by smesnage** [Mesnage-Org/pgfinder#223]
Ecoli_WT(Patel et al).ftrs hurts my eyes
What about:
E. coli WT (Patel et al).ftrs

PPM (GUI) should not be in capitals (it's ppm in the output)

I feel ashamed about this request...

**Comment by TheLostLambda** [comment]
Happy to change file names! I didn't love them either!

Could I convince you to keep the capitals in PPM though? It's an acronym and feels alright to be in capitals since I'm one of the diseased that uses capitals in titles and that's the way all of the other titles are?

**Comment by TheLostLambda** [comment]
Let me know if these look alright!
![image](https://github.com/Mesnage-Org/pgfinder/assets/6251883/7ca4d19c-4fe0-4e8e-ac51-a72456baca13)

**Comment by TheLostLambda** [comment]
Those files are renamed! Let me know if the PPM thing is really killing you though...
