### ISSUE TITLE
Enable additional documentation versions on ReadTheDocs

### ISSUE THREAD

**Issue by ns-rse** [Mesnage-Org/pgfinder#228]
Very quick and easy getting the documentation migrated and built on ReadTheDocs, great work @bobturneruk 

I noticed the sidebar which listed versions was removed.

Reading [the docs (sic)](https://docs.readthedocs.io/en/stable/versions.html) we get multiple versions of the documentation built automagically and so there is currently...

* [latest](https://pgfinder.readthedocs.io/en/latest/)
* [stable](https://pgfinder.readthedocs.io/en/stable/) (which is v1.0.3)

But to enable documentation for specific versions requires adjusting a setting on the ReadTheDocs Project page to enable versions in the [project page](https://readthedocs.org/projects/pgfinder/versions/). I had a go but as I'm not the maintainer can't change this (if you want to add me to the project on ReadTheDocs I'm happy to make the change @bobturneruk ).

**Comment by bobturneruk** [comment]
It's a a bit more complicated - I can activate versions, but they don't get displayed - I think this is a https://github.com/Mesnage-Org/pgfinder/blob/master/docs/conf.py or templating thing. I've added you as a maintainer. @TheLostLambda and @smesnage - I'll add you too but you'll need readthedocs accounts.

**Comment by ns-rse** [comment]
Ok I'll have a look into this, thanks for adding me as a maintainer @bobturneruk :+1:

**Comment by TheLostLambda** [comment]
@bobturneruk I've made an account one RTD with the same username! TheLostLambda

**Comment by ns-rse** [comment]
A little reading around has led me to a possible [solution](https://stackoverflow.com/a/75903554/1444043) but I'm not sure how its going to play with the theme we are currently using.

The other possible solution is I think to use the sidebar which was removed in `docs/conf.py` in #219 although the referenced `_templates/sidebar.html` still persists in the repository and reinstating its use in the configuration may be simpler than the above.

@bobturneruk Was the sidebar causing problems? I've checked the [build history](https://readthedocs.org/projects/pgfinder/builds/) but couldn't see it being the cause of any of the failures.

**Comment by bobturneruk** [comment]
Yes the sidebar was empty. Feel free to reinstate.

**Comment by ns-rse** [comment]
Ah, ok I'll see if I can get it working, thanks.

**Comment by TheLostLambda** [comment]
With the switch to the RTD theme, can this be closed?

**Comment by TheLostLambda** [comment]
It seems to let me pick versions! I'll close this for now!
