### ISSUE TITLE
API Documentation Seems Non-Existant on ReadTheDocs

### ISSUE THREAD

**Issue by TheLostLambda** [Mesnage-Org/pgfinder#239]
Probably one for our documentation wizards @ns-rse and @bobturneruk — for some reason or another, it looks like none of the docstrings are being built into documentation?

All empty in the `pgfinder` module here: https://pgfinder.readthedocs.io/en/latest/api.html

**Comment by TheLostLambda** [comment]
I could be misunderstanding as well, but I'm pretty sure this is a requirement for JOSS? This is probably the last blocker for publication (unless I'm missing something) @smesnage

**Comment by smesnage** [comment]
What do I need to do?
Another thing that I don't understand, we've already writen  that kind of crap, no? Is it not the matter of copying/pasting existing stuff here?

**Comment by TheLostLambda** [comment]
@smesnage Was just a heads-up for you more than anything! And yeah, the documentation should be there, it's just not being correctly built / uploaded to the new documentation website (which I think is something @ns-rse or @bobturneruk probably know best about)!

**Comment by bobturneruk** [comment]
I'll see what I can do.

**Comment by ns-rse** [comment]
I noticed this when fixing the versioning and I thought I'd fixed it in the PR.

I think I know what the cause is likely to be because the `pgfinder` Python code has moved from `pgfinder` > `lib` so its a minor tweak to the `docs/conf.py`. I'll take a look now @bobturneruk

**Comment by TheLostLambda** [comment]
@ns-rse It's possible — probable, even — that I'm just doing something wrong, but I now seem to get all of those summary pages but still none of the documentation pages that show each function, its docstring, and parameters?

I see the first screenshot of #241, but not the second!

**Comment by ns-rse** [comment]
@TheLostLambda I'm guessing you mean its on the readthedocs where you're not seeing the output (I too can't see it now its built). I'm looking through the build logs and will have a tinker (I can enable a build from a branch).

Do the docs build correctly locally for you?

```
# <activate virtual env and ensure you've installed dependencies with pip install -e .[docs]
cd lib/docs
make html
```

It might be that the environment on ReadTheDocs hasn't pulled in the `sphinx-autoapi` packages so I'm going to try adding them.

**Comment by ns-rse** [comment]
[Fixed it](https://pgfinder.readthedocs.io/en/ns-rse-239-api-docs/autoapi/pgfinder/errors/index.html#pgfinder.errors.UserError) :smile: 

(Above is on my branch, PR incoming to get this on `master` and working for all other branches).

**Comment by TheLostLambda** [comment]
@ns-rse Looks great and works for me too! Thanks a ton!

Before closing this, could we resolve one last little nitpick? If it's tricky though, I don't think we need to bother:

Could we get rid of the first-option API now? Leaving just the new, nicer autodoc one? It would clean up some redundancy!
![image](https://github.com/Mesnage-Org/pgfinder/assets/6251883/8081644f-e411-4f3e-aa16-b8a72fa5544d)

The "API Reference" is the good new one you've just added, the "API" is the old one I think we can do without!

Let me know what you think! If we can fix that, I can die happy (and we can finally submit to JOSS)

**Comment by ns-rse** [comment]
Ah, sorry missed that, should only have the `autodoc.extension` one's now and not the `sphinx-ext-autosummary` ones.

**Comment by TheLostLambda** [comment]
I'm temporarily reopening this to remind me to try to fix things!
