### ISSUE TITLE
Add masses for other species

### ISSUE THREAD

**Issue by bobturneruk** [Mesnage-Org/pgfinder#24]

**Comment by Ankur-AVP-Patel** [comment]
Work in progress, C diff mass file completed, E faecalis in the works.

**Comment by bobturneruk** [comment]
Would be great to have a file naming convention here maybe just 

`masses-<short species name>.csv`

e.g.

`masses-ecoli.csv`

Or do we need more information?

**Comment by bobturneruk** [comment]
Put in `masses/` folder.

**Comment by bobturneruk** [comment]
All `.csv` or `.ftrs` need to be deleted or in `data/` or in `masses/`.

**Comment by Ankur-AVP-Patel** [comment]
C diff data file added, E faecalis suspended.
