### ISSUE TITLE
Add an "advanced option" for automated consolidation

### ISSUE THREAD

**Issue by smesnage** [Mesnage-Org/pgfinder#254]

**Comment by smesnage** [comment]
![Consolidation example](https://github.com/Mesnage-Org/pgfinder/assets/70374280/931f7acd-e2d3-431b-bac2-c787a307be27)

**Comment by TheLostLambda** [comment]
Closing this for now, since this is merged and the "advanced option" part can be part of the new cross-replicate consolidation issue!
