### ISSUE TITLE
Fix issues with Svelte Check and linting of package.json

### ISSUE THREAD

**Issue by ns-rse** [Mesnage-Org/pgfinder#262]
Final oustanding PR was [failing](https://github.com/Mesnage-Org/pgfinder/actions/runs/7902634802/job/21568716001?pr=257#step:6:1) because of errors occurring with `pnpm check` and not being able to correctly import from `fa.svelte`

```
Run pnpm check
  pnpm check
  shell: /usr/bin/bash -e {0}
  env:
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin

> pgfinder-gui@0.0.0 check /home/runner/work/pgfinder/pgfinder/web
> svelte-kit sync && svelte-check --tsconfig ./tsconfig.json


====================================
Loading svelte-check in workspace: /home/runner/work/pgfinder/pgfinder/web
Getting Svelte diagnostics...

/home/runner/work/pgfinder/pgfinder/web/src/routes/Tooltip.svelte:[3](https://github.com/Mesnage-Org/pgfinder/actions/runs/7902634802/job/21568716001?pr=257#step:6:3):17
Error: Could not find a declaration file for module 'svelte-fa/src/fa.svelte'. '/home/runner/work/pgfinder/pgfinder/web/node_modules/.pnpm/svelte-fa@3.0.[4](https://github.com/Mesnage-Org/pgfinder/actions/runs/7902634802/job/21568716001?pr=257#step:6:4)/node_modules/svelte-fa/src/fa.svelte' implicitly has an 'any' type. (ts)
	import { popup, type PopupSettings } from '@skeletonlabs/skeleton';
	import Fa from 'svelte-fa/src/fa.svelte';
	import { faCircleInfo } from '@fortawesome/free-solid-svg-icons';


/home/runner/work/pgfinder/pgfinder/web/src/routes/Header.svelte:3:1[7](https://github.com/Mesnage-Org/pgfinder/actions/runs/7902634802/job/21568716001?pr=257#step:6:8)
Error: Could not find a declaration file for module 'svelte-fa/src/fa.svelte'. '/home/runner/work/pgfinder/pgfinder/web/node_modules/.pnpm/svelte-fa@3.0.4/node_modules/svelte-fa/src/fa.svelte' implicitly has an 'any' type. (ts)
	import { AppBar } from '@skeletonlabs/skeleton';
	import Fa from 'svelte-fa/src/fa.svelte';
	import { faBars, faBook } from '@fortawesome/free-solid-svg-icons';


/home/runner/work/pgfinder/pgfinder/web/src/routes/LinksAndDownloads.svelte:3:17
Error: Could not find a declaration file for module 'svelte-fa/src/fa.svelte'. '/home/runner/work/pgfinder/pgfinder/web/node_modules/.pnpm/svelte-fa@3.0.4/node_modules/svelte-fa/src/fa.svelte' implicitly has an 'any' type. (ts)
	import { base } from '$app/paths';
	import Fa from 'svelte-fa/src/fa.svelte';
	import { faDownload } from '@fortawesome/free-solid-svg-icons';


====================================
svelte-check found 3 errors and 0 warnings in 3 files
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```

These were corrected by changing the imports to...

```
import Fa from 'fa.svelte';
```

...in the three affected files.

But we now get [failures](https://github.com/Mesnage-Org/pgfinder/actions/runs/7903024823/job/21569988647?pr=257) when `pnpm lint` is run...

```
Run pnpm lint
  pnpm lint
  shell: /usr/bin/bash -e {0}
  env:
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin

> pgfinder-gui@0.0.0 lint /home/runner/work/pgfinder/pgfinder/web
> prettier --plugin prettier-plugin-svelte --check . && eslint .

Checking formatting...
[warn] package.json
[warn] Code style issues found in the above file. Run Prettier to fix.
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```

I can replicate this error locally and have been trying to run `prettier` locally but it consistently fails to find the [`prettier-plugin-svelte`](https://github.com/sveltejs/prettier-plugin-svelte/) even though it is clearly installed.

This [old issue](https://github.com/sveltejs/prettier-plugin-svelte/issues/155) suggested one resolution may be to add it in a [Prettier configuration file](https://prettier.io/docs/en/configuration) but adding the file `.prettierrc.cjs`

```json
{
    "useTabs": true,
    "singleQuote": true,
    "trailingComma": "none",
    "printWidth": 100,
    "plugins": ["prettier-plugin-svelte"],
    "overrides": [{ "files": "*.svelte", "options": { "parser": "svelte" } }]
}
```

hasn't worked.

Running prettier manually against the `package.json` gives...

```
 ❱ ./node_modules/prettier/bin/prettier.cjs --plugin prettier-plugin-svelte --check package.json
Checking formatting...
[error] Invalid configuration for file "/home/neil/work/git/hub/Mesnage-Org/pgfinder/web/package.json":
[error] Unexpected token ':'
```

I've also tried using the [`pre-commit`](https://pre-commit.com) hook for [`prettier`](https://github.com/pre-commit/mirrors-prettier)
So I'm currently stumped as to...

a) What is wrong with the formatting of `package.json` in the first place.
b) How to resolve this and better still...
c) Get Prettier running as part of CI (whether that is via a dedicated GitHub Action or better still via `pre-commit` hooks).

**Comment by TheLostLambda** [comment]
Not the most helpful piece of input, but you're not alone here. That's something I'd also been struggling with, hence why (unfortunately) I think some of it was disabled.

Perhaps it's still something that can be fixed, but dealing with nodejs bundlers / tooling has led to some of the most miserable I've ever been, so it might be a mission.

**Comment by ns-rse** [comment]
Thanks @TheLostLambda 

I've managed to run `prettier` locally to check what its complaining about in `package.json` and it appears to be...nothing.

```
❱ ./node_modules/prettier/bin/prettier.cjs  -c package.json
Checking formatting...
All matched files use Prettier code style!
```

So unsure what it might be complaining about in CI. :shrug:
