### ISSUE TITLE
Consolidation issue

### ISSUE THREAD

**Issue by smesnage** [Mesnage-Org/pgfinder#274]
Abundance value needs more decimals (currently 2), otherwise consolidation across samples leads to intensities = zero
See average tab, highlighted lines in file attached.
[Cross sample consolidation example.xlsx](https://github.com/Mesnage-Org/pgfinder/files/14648909/Cross.sample.consolidation.example.xlsx)

**Comment by TheLostLambda** [comment]
@smesnage Would you like this coupled with multiplying those values by 100 again? Or keep them between 0 and 1, just with more values?

It looks like we'd need quite a few... At least 5 decimals if they are between 0 and 1, or up 3 if we're multiplying by 100

If you could link these raw files here, then we can make sure whatever number of decimals, that it's enough for this. The other option is just not rounding those numbers at all, and leaving that up to Excel formatting by the user? I don't know if that's a bit too messy though.

Regardless, it's a very easy code change, just let us know what exactly you'd like to see!

**Comment by smesnage** [comment]
The current consolidation does not give sums that equal 100%. I think this is the thing to check. 
I think it is better to leave it as a number between 0 and 1 and add 5 decimals. 
Btw, why not add more?

**Comment by smesnage** [comment]
Also, another problem (sorry) is that during the consilidation, some intensities that are not equal to zero return a 0% abundance...

![image](https://github.com/Mesnage-Org/pgfinder/assets/70374280/a6218d56-acb0-4dc9-b835-9a8c0b2f9aa3)

**Comment by smesnage** [comment]
[file for brooks.xlsx](https://github.com/Mesnage-Org/pgfinder/files/14657615/file.for.brooks.xlsx)

**Comment by TheLostLambda** [comment]
No reason not to add more aside from it looking "messy", but these are probably things we really don't want to lose precision on (they need to be non-zero and sum to 1 always!) so I'll just remove the rounding for the abundances!
