### ISSUE TITLE
Rehome dataframe to csv code

### ISSUE THREAD

**Issue by Ankur-AVP-Patel** [Mesnage-Org/pgfinder#34]
Move lines 333-338 into its own script for outputting results as a csv file.

Add functionality to demo

**Comment by Ankur-AVP-Patel** [comment]
Function added to write dataframe to csv 7dcc00a9defe4abe30f6bf4921a69c8b8889f510

**Comment by bobturneruk** [comment]
Best not to close until pull request is merged.
