### ISSUE TITLE
Function `maxquant_file_reader` appears in `matching.py` and `Maxquant Data Parser.py`

### ISSUE THREAD

**Issue by bobturneruk** [Mesnage-Org/pgfinder#35]
Consider deleting `Maxquant Data Parser.py`?

**Comment by Ankur-AVP-Patel** [comment]
Maxquant Data Parser.py now removed, functionality is now available in maxquant_file_reader in matching.py

**Comment by bobturneruk** [comment]
Best not to close until pull request is merged.
