### ISSUE TITLE
Validation of raw data fails on FTRS file upload

### ISSUE THREAD

**Issue by Ankur-AVP-Patel** [Mesnage-Org/pgfinder#47]
Uploading FTRS file for processing via Mybinder results in the error message 'raw_data_df must be a DataFrame.'

validation.validate_raw_data_df check is being failed. 

Attempting to reproduce test locally unsuccessful.

**Comment by bobturneruk** [comment]
I can replicate this on my laptop.

**Comment by bobturneruk** [comment]
So the problem is that you can't open an sqlite database from bytes in memory, it has to be on disk.
