### ISSUE TITLE
Create a mass calculator 

### ISSUE THREAD

**Issue by smesnage** [Mesnage-Org/pgfinder#62]
The idea is to generate a piece of code that converts a list of muropeptides into a CSV file (muropeptide, monoisotopic mass) that can be used for PGFinder searches
A user friendly version as a Jupyter notebook would be good.

All details and suggestions are detailed in the shared document:
https://docs.google.com/document/d/1kC9G-a1Uj7tMJcYN3qFm4aVAKTsWbF276Ou9HrJ3q3E/edit?usp=sharing

**Comment by bobturneruk** [comment]
Welcome to GitHub @smesnage - we hope you never leave :)

**Comment by Ankur-AVP-Patel** [comment]
Can this issue be closed now that I have approved and merged the mass calc PR?

**Comment by bobturneruk** [comment]
@Ankur-AVP-Patel - not quite yet. Still needs some kind of interface.

**Comment by bobturneruk** [comment]
Moved to another project.
