### ISSUE TITLE
Create a logbook to describe new functionalities (PGFinder versions)

### ISSUE THREAD

**Issue by smesnage** [Mesnage-Org/pgfinder#63]
As we are improving PGFinder, we need to keep track of the improvement we are making. This info should be shared with users so that they can see what has changed between versions. I think a link to some sort of google doc would do the trick. I have added an idea in the shared document.
https://docs.google.com/document/d/1kC9G-a1Uj7tMJcYN3qFm4aVAKTsWbF276Ou9HrJ3q3E/edit?usp=sharing

Maybe having a version number associated with the script run trhough the Jupyter notebook ? PGFinder 1.0.6...
No clue if there is a rule to number releases!! Needs to be investigated. 

See what PMI does!
https://proteinmetrics.com/announcement/version-release-updates/#:~:text=VERSION%204.0%20%7C%20March%2031%2C%202021

**Comment by bobturneruk** [comment]
GitHub has a way to make this easy - but may need some adaptation to fit with how we're delivering this to users using Jupyter.

**Comment by Ankur-AVP-Patel** [comment]
Issue closed, see above comment.
