### ISSUE TITLE
Delete columns in search output

### ISSUE THREAD

**Issue by smesnage** [Mesnage-Org/pgfinder#65]
Delete 4 columns in the search output with FTRS files:

Delete  ID
Delete feature
Delete corrMax
Delete maxisotopeCount

**Comment by smesnage** [comment]
In hindsight, I would keep ID and remove the 3 other columns:

Delete feature
Delete corrMax
Delete maxisotopeCount

**Comment by Ankur-AVP-Patel** [comment]
Changes made in #71, pending merge of #75 to master before rebase of 71 and merge in after baseline update.
