### ISSUE TITLE
Amend modifications names

### ISSUE THREAD

**Issue by smesnage** [Mesnage-Org/pgfinder#66]
Homogeneise names for the following modifications:

Replace De-Ac with DeAc
Replace Anhydro with Anh
Replace De-Acetyl Anhydro with De-Ac Anh

**Comment by Ankur-AVP-Patel** [comment]
Where do these changes need to occur? In the mass files or the notebook interface etc?

**Comment by smesnage** [comment]
Ideally, we want the description of the modifications to be consistent:
- in the database (if included at this stage)
- in the drop-down menu of the notebook (some modifications appear with a different syntax whether they are alone or combined with another one)
- in the output

**Comment by smesnage** [comment]
Got Ankur's blessing to close this as it was solved with #79
