### ISSUE TITLE
Consider further parametersation

### ISSUE THREAD

**Issue by bobturneruk** [Mesnage-Org/pgfinder#7]
Could data in lines like this:

https://github.com/Dr-Encore/Mass-Spec-MS1-Analysis/blob/c2735e8fcf73575d9c7d701f729a465331fefcc9/matching%20v7.py#L206

or this:

https://github.com/Dr-Encore/Mass-Spec-MS1-Analysis/blob/c2735e8fcf73575d9c7d701f729a465331fefcc9/matching%20v7.py#L192

Be stored in files / command line arguments / gui input and then fed into functions? Do they ever change?

**Comment by Ankur-AVP-Patel** [comment]
I'll look into storing both parameters and others like them into a file. 

Both values could change, the first one should be an infrequent as its to do with reordering columns from FTRS files. The sugar mass would change depending on the species being analysed.

**Comment by Ankur-AVP-Patel** [comment]
I believe this has been addressed in #75 and can now be closed.
