### ISSUE TITLE
Change the word "library" for "database in the Jupyter notebook interface!

### ISSUE THREAD

**Issue by smesnage** [Mesnage-Org/pgfinder#70]
See above

**Comment by bobturneruk** [comment]
Thanks for this!!

**Comment by bobturneruk** [comment]
Resolved by an accidental push to master! https://github.com/Mesnage-Org/pgfinder/commit/883788e833922a7e81e00d3cfb58c9c4f3f90f28

**Comment by bobturneruk** [comment]
Probably cause this https://github.com/Mesnage-Org/pgfinder/actions/runs/2496655548 Sorry!
