### ISSUE TITLE
Use pathlib and f-strings throughout for directory and filename manipulation.

### ISSUE THREAD

**Issue by ns-rse** [Mesnage-Org/pgfinder#78]
The [pathlib](https://docs.python.org/3/library/pathlib.html) is an object-orientated module for handling directory paths, filenames and components thereof that works well across OS's and is very convenient to use and understand. Its class `Path()` is recognised by the vast majority of Python libraries and it essentially replaces the need to use the `os` library.

At the same time it works with f-strings (see [PEP-498](https://peps.python.org/pep-0498/)) so anywhere strings are joined to make directory of filenames a `Path()` object and f-strings can be used.

Some useful links on pathlib...

[Why you should be using pathlib - Trey Hunner](https://treyhunner.com/2018/12/why-you-should-be-using-pathlib/)
[No really, pathlib is great - Trey Hunner](https://treyhunner.com/2019/01/no-really-pathlib-is-great/)
[pathlib — Object-oriented filesystem paths — Python 3.10.4 ...](https://docs.python.org/3/library/pathlib.html)

**Comment by bobturneruk** [comment]
This is the way forward.
