### ISSUE TITLE
Create Delta ppm column in the matching output

### ISSUE THREAD

**Issue by smesnage** [Mesnage-Org/pgfinder#80]
Add a column providing ppm difference between observed and theoretical mass  in the search output (add it after theo mass column).
(obs-theo)/theo*1000000 

THis is useful when an observed mass is matched to distinct structures; the right match is often the one with the smallest delta ppm (see example given where I did it manually). One structure is more likely to be the right one based on ppm).

In the case of multiple matches, ppm variation should be provided in a similar way as theoretical matches. Example is below; one structure is more likely to be the right one based on ppm).

[Ppm.pdf](https://github.com/Mesnage-Org/pgfinder/files/8773201/Ppm.pdf)

**Comment by bobturneruk** [comment]
Hi @Ankur-AVP-Patel - I think it's generally better to let people self-assign stuff. This might be a better one for @ns-rse.

**Comment by Ankur-AVP-Patel** [comment]
This issue update was for the meeting we have later to have an example to show. Assignment can be changed to whoever is most appropriate after the meeting.

**Comment by smesnage** [comment]
@ns-rse, Maybe worth holding fire on this until I have a chat with Brooks to see if he can sort this out whilst you work on other stuff.

**Comment by ns-rse** [comment]
I started work on this last Friday (on branch [`ns-rse/80-delta-ppm`](https://github.com/Mesnage-Org/pgfinder/tree/ns-rse/80-delta-ppm)) and have the functionality working but need to get #7 resolved first so that the decimal places are to everyones liking.

**Comment by smesnage** [comment]
4 decimal places are good. 5 might be better but probably overkill

**Comment by smesnage** [comment]
Neither of them! Sorry c

((obs-theo)/theo)*1000000

![image](https://user-images.githubusercontent.com/70374280/232542495-2af6aa29-7ae5-478a-b61c-83429db50962.png)
