### ISSUE TITLE
Add a ChangeLog and include it in the documentation

### ISSUE THREAD

**Issue by ns-rse** [Mesnage-Org/pgfinder#91]
For releases we should include a ChangeLog in the repository and include it in the documentation pages.

[Semantic versioning](https://semver.org/) should be used to number releases.

**Comment by ns-rse** [comment]
Changelogs based on commits can be generated automatically when creating a tagged version for release. That said they're not the best overview a higher level summary could be included in a specific `ChangeLog` file.

**Comment by TheLostLambda** [comment]
Probably a good idea to follow https://keepachangelog.com/en/1.1.0/ when the time comes! I think moving to 1.0.0 should mean starting the changelog then!
